spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpa-shop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create  #애플리케이션 실행 시점에 테이블을 drop하고, 다시 생성
    properties:
      hibernate:
#        show_sql: true  #System.out에 하이버네이트 실행 SQL을 남김
        format_sql: true

logging.level:
  org.hibernate.SQL: debug  #logger를 통해 하이버네이트 실행 SQL을 남김
#  org.hibernate.orm.jdbc.bind: trace  # SQL 실행 파라미터를 로그로 남기기 -> 라이브러리(gavlyukovskiy) 추가가 더 보기 편함

#TrackingModes  URL 전달 방식을 끄고 항상 쿠키를 통해서만 세션을 유지하겠다
server:
  servlet:
    session:
      timeout: 60
      tracking-modes: cookie
